import 'dart:convert';

import 'package:itp_voice/helpers/config.dart';
import 'package:itp_voice/repo/shares_preference_repo.dart';
import 'package:itp_voice/storage_keys.dart';

/// Helpers for building recording-download URLs and parsing the
/// AWS-Transcribe-Call-Analytics JSON blob that the server stores in
/// `call_transcription`.
class CallMedia {
  CallMedia._();

  /// Build a recording URL for [cdrPk]. Returns `null` if we don't have an
  /// API id or access token cached yet (e.g. user just logged out).
  static String? recordingUrl(int? cdrPk) {
    if (cdrPk == null) return null;
    final apiId =
        SharedPreferencesMethod.storage.getString(StorageKeys.API_ID);
    final token =
        SharedPreferencesMethod.storage.getString(StorageKeys.ACCESS_TOKEN) ??
            SharedPreferencesMethod.storage.getString(StorageKeys.REFRESH_TOKEN);
    if (apiId == null || token == null) return null;
    final base = Config.BASE_URL_ITP_VOICE;
    // Note: voice360-fe uses `access_token` but the mobile client historically
    // stores the refresh token under REFRESH_TOKEN. We try access first, fall
    // back to refresh — either is acceptable to the recording endpoint.
    return '$base${apiId}/my-extension/cdr/$cdrPk/download-recording/raw'
        '?token=$token&convert_base64=false';
  }
}

/// A single turn of a parsed call transcript.
class TranscriptTurn {
  final String role; // 'AGENT' | 'CUSTOMER' | 'SYSTEM' (unknown roles fall here)
  final String text;
  final double startSeconds;
  final double endSeconds;

  const TranscriptTurn({
    required this.role,
    required this.text,
    required this.startSeconds,
    required this.endSeconds,
  });

  bool get isAgent => role.toUpperCase() == 'AGENT';
  bool get isCustomer => role.toUpperCase() == 'CUSTOMER';
}

/// Result of parsing a transcription JSON string.
class ParsedTranscript {
  final List<TranscriptTurn> turns;
  final String? summary;
  final int? participantCount;
  final double? totalDurationSeconds;

  const ParsedTranscript({
    required this.turns,
    this.summary,
    this.participantCount,
    this.totalDurationSeconds,
  });

  bool get isEmpty => turns.isEmpty;

  static const ParsedTranscript empty =
      ParsedTranscript(turns: <TranscriptTurn>[]);
}

/// Parses the AWS-Transcribe-Call-Analytics JSON shape the server returns in
/// `call_transcription`. Tolerant: any malformed or missing field falls back
/// to a sensible empty value.
ParsedTranscript parseTranscription(String? raw) {
  if (raw == null || raw.trim().isEmpty) return ParsedTranscript.empty;
  try {
    final root = jsonDecode(raw);
    if (root is! Map) return ParsedTranscript.empty;

    final transcriptRaw = root['Transcript'];
    if (transcriptRaw is! List) return ParsedTranscript.empty;

    final turns = <TranscriptTurn>[];
    for (final entry in transcriptRaw) {
      if (entry is! Map) continue;
      final role = (entry['ParticipantRole'] as String?) ?? 'UNKNOWN';
      final content = (entry['Content'] as String?) ?? '';
      final start = (entry['BeginOffsetMillis'] as num?)?.toDouble() ?? 0;
      final end = (entry['EndOffsetMillis'] as num?)?.toDouble() ?? start;
      if (content.trim().isEmpty) continue;
      turns.add(TranscriptTurn(
        role: role,
        text: content,
        startSeconds: start / 1000.0,
        endSeconds: end / 1000.0,
      ));
    }

    String? summary;
    try {
      summary = root['ConversationCharacteristics']?['ContactSummary']
          ?['AutoGenerated']?['OverallSummary']?['Content'] as String?;
    } catch (_) {
      summary = null;
    }

    int? participantCount;
    final participants = root['Participants'];
    if (participants is List) participantCount = participants.length;

    final last = turns.isEmpty ? null : turns.last;
    return ParsedTranscript(
      turns: turns,
      summary: (summary != null && summary.trim().isNotEmpty) ? summary : null,
      participantCount: participantCount,
      totalDurationSeconds: last?.endSeconds,
    );
  } catch (_) {
    return ParsedTranscript.empty;
  }
}
